# Geocoding


Geocoding is the conversion of addresses into geographic coordinates, typically `latitude and longitude`. It enables mapping and location-based services by associating a physical location with a given address. Reverse geocoding, on the other hand, does the opposite, translating coordinates back into a human-readable address.

In [1]:

import numpy as np 
import pandas as pd 
import folium 
from geopy.geocoders import Nominatim

In [5]:
data = {
    'Capital': ['Washington, D.C.', 'Ottawa', 'Berlin', 'Paris', 'Tokyo', 'New Delhi', 'Brasília', 'Canberra', 'Beijing', 'Pretoria'],
}

# Create a Pandas DataFrame
df = pd.DataFrame(data)

# df.loc[len(df)] = {'Capital': abc}

df

            Capital
0  Washington, D.C.
1            Ottawa
2            Berlin
3             Paris
4             Tokyo
5         New Delhi
6          Brasília
7          Canberra
8           Beijing
9          Pretoria

In [57]:
geolocator = Nominatim(user_agent="notebook")

for index,row in df.iterrows():
    try:
        df.loc[index,'Country'] = geolocator.geocode(row[0]).address.split(',')[-1].strip()
        df.loc[index,'Latitude'] = geolocator.geocode(row[0]).point.latitude
        df.loc[index,'Longitude'] = geolocator.geocode(row[0]).point.longitude
    except Exception as e:
        print(e)
    
df

             Capital        Country   Latitude   Longitude
0   Washington, D.C.  United States  38.895037  -77.036543
1             Ottawa         Canada  45.420878  -75.690111
2             Berlin    Deutschland  52.517037   13.388860
3              Paris         France  48.853495    2.348391
4              Tokyo             日本  35.684057  139.774491
5          New Delhi          India  28.613895   77.209006
6           Brasília         Brasil -10.333333  -53.200000
7           Canberra      Australia -35.297591  149.101268
8            Beijing             中国  39.905714  116.391297
9           Pretoria   South Africa -25.745928   28.187910
10            Idukki          India   9.832436   76.998120